spring:
  h2:
    console:
      enabled: false
  config:
    import: 'aws-parameterstore:'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: mysql
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: {AWS RDS Endpoint}
    username: {RDS Mysql Admin id}
    password: {RDS Mysql Admin password}

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: { Google Client Id }
            clientSecret: { Google Client Secret }
            scope:
              - email
              - profile
aws:
  paramstore:
    enabled: true
    prefix: /spring-boot-aws
    profile-separator: _
    name: albamung

security:
  jwt:
    token:
      secret-key: { jwt Secret Key }
      expire-length: 300000

clientUri: https://albamung.tk