spring:
  jpa:
    hibernate:
      ddl-auto: update  # (1) 스키마 자동 생성
    show-sql: true      # (2) SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: {AWS RDS Endpoint}
    username: {RDS Mysql Admin id}
    password: {RDS Mysql Admin password}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: { Google Client Id }
            clientSecret: { Google Client Secret }
            scope:
              - email
              - profile
  config:
    import: aws-parameterstore


security:
  jwt:
    token:
      secret-key: { jwt Secret Key }
      expire-length: 300000
server:
  error:
    include-message: always
  servlet:
    encoding:
      force-response: true
clientUri: http://pre-project-client39.s3-website.ap-northeast-2.amazonaws.com/